eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    username: root
    driver-class-name: com.mysql.jdbc.Driver
rr:
user: 123
